### ISSUE TITLE
Add service to encapsulate interaction with local storage

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-angular1#67]
app.http.interceptor and login.controller interact directly with localStorage. There may be other places, but these come to mind.

Introduce a local storage service to handle the low-level details.

**Comment by jcornfusionalliance** [comment]
to paraphrase from clean code : 

High level modules should not depend on low level modules, they should depend on abstractions. 

I just wrote an "AuthService" in my last pull request. 

I agree that we need a service for that, but I will want to use it in my new AuthService as well because it also interacts directly. 

I'll build this PR into my existing PR for the user_drop_down menu since I already saw the need for an AuthService.

**Comment by JakeTheCorn** [comment]
@BWortman 

after feature/user_drop_down gets merged this issue can be closed. 

Thanks!

**Comment by BWortman** [comment]
Closed with PR #72
